fusion-energy/neutronics-workshop

Dockerfile
Python package was not installing, so it has been removed
=> removed plasma source

Dockerfile, tasks/task_02_making_materials/1_example_materials_from_isotopes.ipynb, tasks/task_02_making_materials/2_example_materials_from_elements.ipynb, tasks/task_02_making_materials/3_example_materials_from_material_maker.ipynb, tasks/task_04_make_sources/2_ring_source.ipynb, tasks/task_10_making_CAD_geometry/1_make_CAD_shapes_from_points.ipynb, tasks/task_10_making_CAD_geometry/2_make_CAD_components_from_parameters.ipynb, tasks/task_10_making_CAD_geometry/3_make_CAD_reactors.ipynb, tasks/task_11_CAD_cell_tally_heat/1_simulate_CAD_neutronics_geometry_with_cell_tally_heat.ipynb
Just keeping a few of the later tasks upto date.
Shape.solid -> Shape.show()
=> updated cad tasks for new paramak/paramak-neutronics

.github/workflows/ci_tests.yml, README.md
=> changedpytest dir

tasks/task_11_CAD_cell_tally_heat/1_simulate_CAD_neutronics_geometry_with_cell_tally_heat.ipynb, tasks/task_12_CAD_mesh_fast_flux/1_making_shapes_into_a_neutronics_model.ipynb, tasks/task_12_CAD_mesh_fast_flux/2_making_components_into_a_neutronics_model.ipynb, tasks/task_12_CAD_mesh_fast_flux/3_making_parametric_reactors_into_a_neutronics_model.ipynb
replacing .solid with .show() and changed the use of neutronics material maker
=> updating task 11 and 12

tasks/task_01_cross_sections/1_isotope_xs_plot.ipynb, tasks/task_01_cross_sections/2_element_xs_plot.ipynb, tasks/task_01_cross_sections/3_material_xs_plot.ipynb
Adding some more definitions, units, equations and discussion on the microscope and macroscopic cross section plotting for task 1 as suggested in issue  #11 
Thanks for the feedback @py1sl
=> added micro & macro scopic xs description

Dockerfile
This PR adds an option to allow the Dockerfile to be built without Double Down
While Double Down offers a nice improvement to the speed it appears to not work well with Manjaro https://openmc.discourse.group/t/dagmc-geometry-open-mc-aborted-unexpectedly/1369/5
updated build instructions are included in the Dockerfile header but to build without double down users can ...
```bash
docker build -t fusion-energy/neutronics-workshop --build-arg include_double_down=OFF .
```
=> added option to not include DD

README.md, tasks/task_01_cross_sections/README.md, tasks/task_02_making_materials/README.md, tasks/task_03_making_CSG_geometry/README.md, tasks/task_04_make_sources/README.md, tasks/task_05_CSG_cell_tally_TBR/README.md, tasks/task_06_CSG_cell_tally_DPA/README.md, tasks/task_07_CSG_cell_tally_spectra/README.md, tasks/task_08_CSG_mesh_tally/README.md, tasks/task_09_CSG_surface_tally_dose/README.md, tasks/task_10_making_CAD_geometry/README.md, tasks/task_11_CAD_cell_tally_heat/README.md, tasks/task_13_parameter_study_sampling/README.md, tasks/task_14_parameter_study_optimisation/README.md
not sure how this happened but all the slides.com links were outdated
=> fixing broken links

.github/workflows/docker-publish-dev.yml, .github/workflows/docker-publish.yml, Dockerfile
allows versions without double down and embree to be built
=> updated to allow different dockerfiles with double-down and embree

Dockerfile
mainly changing the cmd to use lab instead of notebook
=> using jupyter lab instead of notebook

tasks/README.md, tasks/task_02_making_materials/3_example_materials_from_material_maker.ipynb, tasks/task_06_CSG_cell_tally_DPA/README.md, tasks/task_10_making_CAD_geometry/1_make_CAD_shapes_from_points.ipynb
jupyter lab has a file browser so this could simplify some of the downloading of links we currently do
=> Fixing old links and moving to Jupyter Lab :tada: 

.github/workflows/ci_tests.yml, tasks/task_11_CAD_cell_tally_heat/1_simulate_CAD_neutronics_geometry_with_cell_tally_heat.ipynb, tasks/task_14_activation_transmutation/README.md, tasks/task_15_parameter_study_sampling/README.md, tasks/task_16_parameter_study_optimisation/README.md, tests/test_task_14.py
minor updates to the readme files
fixed links 
improved activation task text
=> updated readme links and text

tasks/task_02_making_materials/4_example_materials_parameter_study.ipynb
It appears that this graph is actually showing temperature in K (and not C).
=> Fix typo in task_02 (temperature in K not C)

tasks/task_03_making_CSG_geometry/1_simple_csg_geometry.ipynb
These two comments (in tasks/task_03_making_CSG_geometry/1_simple_csg_geometry.ipynb) didn't make any sense in this code block.  There are similar comments in a later code block which do make sense there.
=> Delete misplaced comments

tasks/task_02_making_materials/5_example_materials_mixed.ipynb
just changing the names of a few materials to be consistent in the example
=> using mat for material names

tasks/task_12_CAD_mesh_fast_flux/1_making_shapes_for_a_3d_mesh_tally_vtk.ipynb, tasks/task_12_CAD_mesh_fast_flux/2_making_components_for_a_2d_mesh_tally_vtk.ipynb, tasks/task_12_CAD_mesh_fast_flux/3_making_reactor_for_a_2d_mesh_tally_and_matplotlib_png.ipynb
simplifies the use of dagmc geometry
=> using bound_universe method for dag geometry

tasks/task_04_make_sources/4_neutron_tracks.ipynb
a user spotted and reported a bug in this example , much appreciated
=> updated to include track filters

tests/test_task_12.py, tests/test_task_4.py, tests/test_task_8.py
tis pr attemps to get the CI green again
=> Reduce ci scope

Dockerfile, tasks/task_14_activation_transmutation_depletion/1_example_transmutation_isotope_build_up.ipynb, tasks/task_14_activation_transmutation_depletion/2_example_tally_change_with_burnup.ipynb
=> increase particles

tasks/task_01_cross_sections/1_isotope_xs_plot.ipynb, tasks/task_01_cross_sections/3_material_xs_plot.ipynb
The latex rendering in task 1 was not working. This PR fixes it
=> Latex fixes in task 1

tasks/task_04_make_sources/4_neutron_tracks.ipynb
If [this PR ](https://github.com/openmc-dev/openmc/pull/2171)is merged then I can tidy up this tracks example a little bit
=> simplified method of writing tracks files to vtk

tasks/task_04_make_sources/1_point_source_plots.ipynb, tasks/task_04_make_sources/2_ring_source.ipynb, tasks/task_04_make_sources/3_plasma_source_plots.ipynb, tasks/task_04_make_sources/5_gamma_source_example.ipynb
simplifies the source plotting a bit by using a nice new package
=> plotting using openmc_source_plotter 0.6.1

Dockerfile, tasks/task_14_activation_transmutation_depletion/1_example_transmutation_isotope_build_up.ipynb
also using the openmc depletion plotter package https://github.com/fusion-energy/openmc_depletion_plotter
=> changed depletion example to Ag instead of Co

tasks/task_14_activation_transmutation_depletion/1_example_transmutation_isotope_build_up.ipynb, tasks/task_14_activation_transmutation_depletion/2_example_tally_change_with_burnup.ipynb
Making use of the new feature in openmc to set chain file using the config
https://github.com/openmc-dev/openmc/pull/2211
=> using new config option

README.md
just changed the order of install advice
=> [skip ci] local install over codespaces

tasks/task_05_CSG_cell_tally_TBR/1_example_tritium_production.ipynb
makes the tbr simulation a bit more interesting but adding contribution from li6 and li7 isotopes to the tbr
=> added li6 li7 tbr values

README.md, tasks/task_17_detectors_examples/1_time_filter_tally.py, tasks/task_17_detectors_examples/2_time_filter_tally_with_reflective_sphere.py, tasks/task_17_detectors_examples/timefilter_diagram.svg
Just made a quick example of a time filter, perhaps the start of some more useful detector examples.
=> Adding time filter detector example

tasks/task_01_cross_sections/1_isotope_xs_plot.ipynb, tasks/task_01_cross_sections/2_element_xs_plot.ipynb, tasks/task_01_cross_sections/3_material_xs_plot.ipynb, tasks/task_01_cross_sections/4_Doppler_broadening.ipynb, tasks/task_02_making_materials/1_example_materials_from_isotopes.ipynb, tasks/task_03_making_CSG_geometry/1_simple_csg_geometry.ipynb, tasks/task_04_make_sources/1_point_source_plots.ipynb, tasks/task_05_CSG_cell_tally_TBR/1_example_tritium_production.ipynb, tasks/task_06_CSG_cell_tally_DPA/1_find_dpa.ipynb, tasks/task_07_CSG_cell_tally_spectra/2_example_neutron_spectra_on_cell.ipynb, tasks/task_08_CSG_mesh_tally/1_example_2d_mesh_tallies.ipynb, tasks/task_10_making_CAD_geometry/1_make_CAD_shapes_from_points.ipynb
thanks to @billingsley-john for showing me this IFrame improvement
=> changed html to iframe

.devcontainer/Dockerfile, .devcontainer/base.Dockerfile
general update to the docker file
=> Updated nuc data and versions in dockerfile

README.md, tasks/task_06_CSG_cell_tally_DPA/1_find_dpa.ipynb, tasks/task_18_stochastic_volume_calculation/1_find_volume_of_cell.ipynb
=> removed dpa from vol calc

tasks/task_13_variance_reduction/shielded_room_survival_biasing.py
This example builds upon a previous shield room model
air cells are added all the way around the outside
source is set to 2.5MeV neutrons
particles per second is not the same for the with Survival_Biasing and without Survival_Biasing simulation
TODO add code comments
with out Survival_Biasing VR
with Survival_Biasing VR
=> added sb vr example

tasks/task_03_making_CSG_geometry/3_viewing_the_geometry_as_vtk.ipynb
this currently needs the development branch of openmc to run
=> simpler voxel plotting

tasks/task_09_CSG_dose_tallies/shut_down_dose_rate_example.py
This is a second attempt at creating a R2S shut down dose rate example. The first one on PR #177 got a bit complicated.
=> simple r2s example

tasks/task_14_activation_transmutation_depletion/1_example_transmutation_isotope_build_up.ipynb
just removing an unused line of code
=> removed_unused_line

.devcontainer/base.Dockerfile, README.md
there appears to be an issue with vtk so this PR pins the version used
more details
https://openmc.discourse.group/t/error-converting-tally-results-to-vtk-file/3355/4
we can see if task 3 passes the CI
=> pinned vtk to 9.2.5

tasks/task_09_CSG_dose_tallies/shut_down_dose_rate_example.py
@eepeterson I have started tidying up the r2s example
=> added comment and plotting and units to r2s example

tasks/task_10_activation_transmutation_depletion/3_full_pulse_schedule.py, tasks/task_11_CSG_shut_down_dose_tallies/2_faster_mulitiple_puse_shut_down_dose_rate_example.py
set energy to a single bin from 0-30MeV
=> correcting energy argument in microxs

tasks/task_06_CSG_cell_tally_DPA/1_find_dpa.ipynb
Update: all outputs have been cleared.
=> Update 1_find_dpa.ipynb (clear outputs)

tasks/task_14_variance_reduction/1_shielded_room_survival_biasing.ipynb, tasks/task_14_variance_reduction/2_shielded_room_single_ww.ipynb, tasks/task_14_variance_reduction/3_sphere_iterative_per_run_ww.ipynb, tasks/task_14_variance_reduction/4_sphere_iterative_per_batch_ww.ipynb
I have corrected some spelling mistakes in the variance reduction tasks.  No changes to python have been made just to markdown.  No tests have been added as no python was changed.
=> Corrected spelling in task 14

.devcontainer/Dockerfile, tasks/task_04_make_sources/1_point_source_plots.ipynb, tasks/task_04_make_sources/2_ring_source.ipynb, tasks/task_04_make_sources/3_plasma_source_plots.ipynb, tasks/task_04_make_sources/5_gamma_source_example.ipynb
The api changed so we should update a few of the examples and rebuild the docker image
=> Update to work with openmc-source-plotter 0.7.0
